### ISSUE TITLE
from decorators import memoized

### ISSUE THREAD

**Issue by bharat1992-bit** [madcat1991/knapsack#2]
Hi ,

when I am running your dynamic programming code I always get an error that cannot import memorized. 
I check for the solution on google and many of the answers said that there are versions compatibility issues. 
I tried to do that also like changing the Django version and Django crispy form version but still it shows the same error. 

Can you please suggest changes.

**Comment by madcat1991** [comment]
Hi, it seems that you have some problems with your IDE. I don't use Django in this project. You can find the `memoized` function in the `decorators.py` file inside the repo.
